#!/usr/bin/env python

'''
description:    Create a db entry for a VOEvent: Runner
license:        APACHE 2.0
author:         Ronald van Haren, NLeSC (r.vanharen@esciencecenter.nl)
'''

import argparse
from pyfrbcatdb import create_VOEvent as pAcreate


def cli_parser():
    '''
    parse command line arguments:
        should be single/multiple valid VOEvent xml files
    '''
    parser = argparse.ArgumentParser(description='Process VOEvent XML file '
                                     'and add it to FRB database')
    parser.add_argument('VOEvents', metavar='VOEvent',
                        type=argparse.FileType('rb'), nargs='+',
                        help='List of VOEvent XML files')
    results = vars(parser.parse_args())['VOEvents']
    return results


if __name__ == "__main__":
    voevents = cli_parser()
    for voevent in voevents:  # TODO: do we allow multiple xml files?
        vo_data, mapping = pAcreate.process_VOEvent(voevent)
