#!/usr/bin/env python

'''
description:    Decode VOEvent db entry to xml: Runner
license:        APACHE 2.0
author:         Ronald van Haren, NLeSC (r.vanharen@esciencecenter.nl)
'''

import argparse
from pyfrbcatdb import decode_VOEvent as pFdecode


def cli_parser():
    '''
    parse command line arguments:
    '''
    parser = argparse.ArgumentParser(description='Process VOEvent XML file '
                                     'and add it to FRB database')
    parser.add_argument('frb_ids', metavar='frb_ids',
                        type=int, nargs='+',
                        help='List of frbs ids')
    return vars(parser.parse_args())['frb_ids']


if __name__ == "__main__":
    frb_ids = cli_parser()
    pFdecode.decode_FRBCat_entry(frb_ids)
